plugin:
    name: 'codecycler.harvest::lang.plugin.name'
    description: 'codecycler.harvest::lang.plugin.description'
    author: 'Sebastiaan Kloos'
    icon: oc-icon-clock-o
    homepage: ''
permissions:
    codecycler.harvest.access_settings:
        tab: 'codecycler.harvest::lang.plugin.name'
        label: 'Access settings'
